theme: minima

plugins:
  - jemoji

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/coloredcow" }
    - { platform: twitter, user_url: "https://twitter.com/coloredcowhq" }
    - { platform: instagram, user_url: "https://www.instagram.com/coloredcow" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/company/6579196" }
    - { platform: facebook, user_url: "https://www.facebook.com/ColoredCowConsulting" }
    
